package com.qrscanner.app.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/**
 * DAO for [RdAccount]. Mirrors the sync surface of [RdNumberDao] +
 * [ScanSessionDao] (push helpers, pull-merge helpers, retry+abandon
 * circuit breaker) so the existing [com.qrscanner.app.data.sync.SyncRepository]
 * machinery applies uniformly.
 *
 * The natural primary key is `rdNumber` (not autoGenerated Long), so
 * the DAO works in rdNumber strings throughout — there is no
 * `findById(Long)` analogue.
 */
@Dao
interface RdAccountDao {

    // ── Browse + observe ─────────────────────────────────────────────

    /**
     * All accounts (active + inactive) excluding tombstones, sorted by
     * name (case-insensitive). Used by the portal-equivalent
     * Accounts screen with the "Show inactive" toggle in client filter.
     */
    @Query("SELECT * FROM rd_accounts WHERE deletedAt IS NULL ORDER BY LOWER(name) ASC")
    fun observeAll(): Flow<List<RdAccount>>

    /** Active accounts only (default list). */
    @Query("SELECT * FROM rd_accounts WHERE deletedAt IS NULL AND isActive = 1 ORDER BY LOWER(name) ASC")
    fun observeActive(): Flow<List<RdAccount>>

    /** Inactive accounts (revealed by the "Show inactive" toggle). */
    @Query("SELECT * FROM rd_accounts WHERE deletedAt IS NULL AND isActive = 0 ORDER BY LOWER(name) ASC")
    fun observeInactive(): Flow<List<RdAccount>>

    @Query("SELECT COUNT(*) FROM rd_accounts WHERE deletedAt IS NULL AND isActive = 1")
    fun observeActiveCount(): Flow<Int>

    @Query("SELECT COUNT(*) FROM rd_accounts WHERE deletedAt IS NULL AND isActive = 0")
    fun observeInactiveCount(): Flow<Int>

    /**
     * Lookup by primary key. Returns null when the account doesn't
     * exist OR is tombstoned (callers can't act on a hard-deleted row).
     * Used by:
     *  - AddAccountsScreen duplicate flag (returns the existing row
     *    so the helper-text can render "Already used by [Name]")
     *  - DefaulterEditDialog auto-suggest (reads lastPaidThrough)
     *  - RDScannerScreen scan handler (auto-reactivate hook)
     */
    @Query("SELECT * FROM rd_accounts WHERE rdNumber = :rdNumber AND deletedAt IS NULL LIMIT 1")
    suspend fun findByRdNumber(rdNumber: String): RdAccount?

    /**
     * Lookup INCLUDING tombstones. Used by the bulk CSV upload path
     * to decide between INSERT-vs-resurrect: a tombstoned row with the
     * same rdNumber should be revived by clearing deletedAt rather
     * than blocked by PK conflict.
     */
    @Query("SELECT * FROM rd_accounts WHERE rdNumber = :rdNumber LIMIT 1")
    suspend fun findByRdNumberIncludingDeleted(rdNumber: String): RdAccount?

    /** Resolve a cloud UUID to its local rdNumber for pull-merge. */
    @Query("SELECT * FROM rd_accounts WHERE cloudId = :cloudId LIMIT 1")
    suspend fun findByCloudId(cloudId: String): RdAccount?

    // ── Local writes (NOT auto-DIRTY — callers must flip syncStatus) ─

    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(account: RdAccount)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertReplace(account: RdAccount)

    @Update
    suspend fun update(account: RdAccount)

    /**
     * Manual-row edit from the Accounts screen edit dialog. Touches
     * name + monthlyAmount + isActive only; the rdNumber PK is locked
     * after creation. Marks DIRTY for sync.
     *
     * Resets retryCount = 0 — any pending edit gets a fresh circuit-
     * breaker window. Without this reset, an account previously
     * abandoned (retryCount >= PUSH_ABANDON_THRESHOLD) would
     * immediately re-abandon on its next push failure even after the
     * user explicitly edited it (oracle bg_6543c8c7 S11).
     */
    @Query(
        """
        UPDATE rd_accounts SET
            name = :name,
            monthlyAmount = :monthlyAmount,
            isActive = :isActive,
            updatedAt = :updatedAt,
            syncStatus = 'DIRTY',
            retryCount = 0
        WHERE rdNumber = :rdNumber AND deletedAt IS NULL
        """
    )
    suspend fun editManualRow(
        rdNumber: String,
        name: String,
        monthlyAmount: Int,
        isActive: Boolean,
        updatedAt: Long
    ): Int

    /**
     * Mark Inactive — sets isActive = 0 + DIRTY for sync push. Does
     * NOT touch accountClosingDate (per user: "they are independent").
     * Resets retryCount per the editManualRow rationale.
     */
    @Query(
        """
        UPDATE rd_accounts SET
            isActive = 0,
            updatedAt = :updatedAt,
            syncStatus = 'DIRTY',
            retryCount = 0
        WHERE rdNumber = :rdNumber AND deletedAt IS NULL AND isActive = 1
        """
    )
    suspend fun markInactive(rdNumber: String, updatedAt: Long): Int

    /**
     * Reactivate — flips isActive = 1 + DIRTY. Called by:
     *  - Accounts edit dialog when user toggles Active back on
     *  - RDScannerScreen scan-success path when an inactive RD is
     *    scanned (auto-reactivate per user request)
     * Resets retryCount per the editManualRow rationale.
     */
    @Query(
        """
        UPDATE rd_accounts SET
            isActive = 1,
            updatedAt = :updatedAt,
            syncStatus = 'DIRTY',
            retryCount = 0
        WHERE rdNumber = :rdNumber AND deletedAt IS NULL AND isActive = 0
        """
    )
    suspend fun reactivate(rdNumber: String, updatedAt: Long): Int

    /**
     * Hard-delete path (the "I added this by mistake" branch of the
     * delete-or-inactivate modal). Soft-tombstone locally first +
     * DIRTY so the push worker propagates `deleted_at` to cloud; the
     * row stays in Room until the next pull confirms the tombstone
     * landed, mirroring the existing session/lot/rd_number delete
     * pattern. retryCount reset per the editManualRow rationale.
     */
    @Query(
        """
        UPDATE rd_accounts SET
            deletedAt = :now,
            updatedAt = :now,
            syncStatus = 'DIRTY',
            retryCount = 0
        WHERE rdNumber = :rdNumber AND deletedAt IS NULL
        """
    )
    suspend fun softDelete(rdNumber: String, now: Long): Int

    /**
     * Resurrect a soft-deleted account in place. Called by
     * AddAccountsScreen when a user adds an account whose rdNumber
     * matches an existing tombstone — we update in place instead of
     * INSERT (which would PK-conflict) so the user's intent persists
     * and the cloud sees a single row transitioning from deleted ->
     * alive (oracle bg_6543c8c7 S4).
     */
    @Query(
        """
        UPDATE rd_accounts SET
            name = :name,
            monthlyAmount = :monthlyAmount,
            source = :source,
            isActive = 1,
            deletedAt = NULL,
            updatedAt = :updatedAt,
            syncStatus = 'DIRTY',
            retryCount = 0
        WHERE rdNumber = :rdNumber AND deletedAt IS NOT NULL
        """
    )
    suspend fun resurrectTombstone(
        rdNumber: String,
        name: String,
        monthlyAmount: Int,
        source: String,
        updatedAt: Long
    ): Int

    /**
     * Monotonic upsert of [RdAccount.lastPaidThrough] for a single
     * account. Updates only when the new value is strictly greater
     * than the current (string comparison works because YYYY-MM
     * tokens sort lexically the same as chronologically). Marks
     * DIRTY for sync. Called by
     * [com.qrscanner.app.data.sync.SyncRepository.markSessionForSync].
     */
    @Query(
        """
        UPDATE rd_accounts SET
            lastPaidThrough = :newMonth,
            updatedAt = :updatedAt,
            syncStatus = 'DIRTY'
        WHERE rdNumber = :rdNumber
          AND deletedAt IS NULL
          AND (lastPaidThrough IS NULL OR lastPaidThrough < :newMonth)
        """
    )
    suspend fun updateLastPaidThroughMonotonic(
        rdNumber: String,
        newMonth: String,
        updatedAt: Long
    ): Int

    // ── Sync push helpers (mirror RdNumberDao) ────────────────────────

    /**
     * Returns DIRTY + SYNC_ERROR accounts (excludes SYNC_ABANDONED per
     * Phase 5 R3 circuit breaker), ordered by updatedAt ASC so the
     * oldest pending edit pushes first.
     */
    @Query(
        """
        SELECT * FROM rd_accounts
        WHERE syncStatus IN ('DIRTY','SYNC_ERROR')
        ORDER BY updatedAt ASC
        LIMIT :limit
        """
    )
    suspend fun getDirtyForPush(limit: Int = 500): List<RdAccount>

    @Query("SELECT COUNT(*) FROM rd_accounts WHERE syncStatus IN ('DIRTY','SYNC_ERROR')")
    fun observePendingCount(): Flow<Int>

    @Query("UPDATE rd_accounts SET syncStatus = 'SYNCING' WHERE rdNumber = :rdNumber AND syncStatus IN ('DIRTY','SYNC_ERROR')")
    suspend fun markSyncing(rdNumber: String)

    /** See [ScanSessionDao.stampCloudId]. */
    @Query("UPDATE rd_accounts SET cloudId = COALESCE(cloudId, :cloudId) WHERE rdNumber = :rdNumber")
    suspend fun stampCloudId(rdNumber: String, cloudId: String)

    @Query(
        """
        UPDATE rd_accounts SET
            syncStatus = 'SYNCED',
            syncedAt = :syncedAt,
            cloudId = COALESCE(cloudId, :cloudId),
            lastSyncError = NULL,
            retryCount = 0
        WHERE rdNumber = :rdNumber
        """
    )
    suspend fun markSynced(rdNumber: String, syncedAt: Long, cloudId: String)

    @Query(
        """
        UPDATE rd_accounts SET
            syncStatus = 'SYNC_ERROR',
            lastSyncError = :error,
            retryCount = retryCount + 1
        WHERE rdNumber = :rdNumber
        """
    )
    suspend fun markSyncError(rdNumber: String, error: String)

    /** See [ScanSessionDao.markSyncAbandoned]. */
    @Query("UPDATE rd_accounts SET syncStatus = 'SYNC_ABANDONED' WHERE rdNumber = :rdNumber")
    suspend fun markSyncAbandoned(rdNumber: String)

    @Query("UPDATE rd_accounts SET syncStatus = 'DIRTY' WHERE syncStatus = 'SYNCING'")
    suspend fun recoverStuckSyncing()

    // ── Pull merge helpers ────────────────────────────────────────────

    /**
     * LWW merge by `rdNumber` PK. Strict < (not <=) per spec §11
     * tie-breaker rule (Phase 5 T5.7): local wins on equal
     * `updatedAt` so a local DIRTY edit racing with the cloud echo of
     * itself survives.
     *
     * Resets retryCount = 0: a row that was SYNC_ABANDONED locally
     * (retryCount >= PUSH_ABANDON_THRESHOLD) but then fixed via
     * portal/CSV upload should NOT immediately re-abandon on its next
     * local-edit failure. Without the reset, the user "fixes" the row
     * from the portal, edits it on the phone, and the very first push
     * failure flips the row back to SYNC_ABANDONED. The reset gives
     * each merged row a fresh circuit-breaker window.
     */
    @Query(
        """
        UPDATE rd_accounts SET
            cloudId = :cloudId,
            name = :name,
            monthlyAmount = :monthlyAmount,
            lastPaidThrough = :lastPaidThrough,
            source = :source,
            isActive = :isActive,
            accountOpenedDate = :accountOpenedDate,
            accountClosingDate = :accountClosingDate,
            ownerId = :ownerId,
            lastEditorDeviceId = :lastEditorDeviceId,
            syncStatus = 'SYNCED',
            updatedAt = :updatedAt,
            syncedAt = :updatedAt,
            lastSyncError = NULL,
            retryCount = 0,
            deletedAt = :deletedAt
        WHERE rdNumber = :rdNumber AND updatedAt < :updatedAt
        """
    )
    suspend fun mergeFromCloud(
        rdNumber: String,
        cloudId: String,
        name: String,
        monthlyAmount: Int,
        lastPaidThrough: String?,
        source: String,
        isActive: Boolean,
        accountOpenedDate: String?,
        accountClosingDate: String?,
        ownerId: String,
        lastEditorDeviceId: String?,
        updatedAt: Long,
        deletedAt: Long?
    ): Int
}
